# Generated by Django 4.0.3 on 2022-06-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('success', models.BooleanField(default=False)),
                ('total', models.FloatField(default=0)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('payid', models.CharField(max_length=100, null=True)),
                ('extras', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
