CANCEL = 1
PENDING = 2
CONFIRMED = 3
SHIPPING = 4
COMPLETED = 5

ORDER_STATUS = [
    (CANCEL, 'CANCEL'),
    (PENDING, 'PENDING'),
    (CONFIRMED, 'CONFIRMED'),
    (SHIPPING, 'SHIPPING'),
    (COMPLETED, 'COMPLETED'),
]
