# Generated by Django 4.0.3 on 2022-04-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Product')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, max_length=12, verbose_name='Price')),
                ('stock', models.DecimalField(decimal_places=4, max_digits=8, max_length=8, verbose_name='Stok')),
                ('unit', models.CharField(choices=[('QTY', 'QTY'), ('KG', 'KG'), ('ITEM', 'ITEM')], default='QTY', max_length=5, verbose_name='Unit')),
            ],
        ),
    ]
