# Generated by Django 4.0.3 on 2022-06-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('title', models.CharField(max_length=160, verbose_name='Product')),
                ('sku', models.CharField(max_length=12, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, max_length=12, verbose_name='Price')),
                ('stock', models.DecimalField(decimal_places=4, max_digits=8, max_length=8, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('QTY', 'QTY'), ('ITEM', 'ITEM'), ('KG', 'KG')], default='QTY', max_length=5, verbose_name='Unit')),
                ('img', models.ImageField(max_length=120, upload_to='uploads/images')),
                ('brand', models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand', to='brand.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
