# Generated by Django 4.0.3 on 2022-06-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('QTY', 'QTY'), ('KG', 'KG'), ('ITEM', 'ITEM')], default='QTY', max_length=5, verbose_name='Unit'),
        ),
    ]
