# Generated by Django 4.0.3 on 2022-04-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_unit_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Brand Name')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('ITEM', 'ITEM'), ('KG', 'KG'), ('QTY', 'QTY')], default='QTY', max_length=5, verbose_name='Unit'),
        ),
    ]
