# Generated by Django 4.0.3 on 2022-05-12 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, max_length=120, upload_to='uploads/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('ITEM', 'ITEM'), ('QTY', 'QTY'), ('KG', 'KG')], default='QTY', max_length=5, verbose_name='Unit'),
        ),
    ]
