# Generated by Django 4.0.3 on 2022-05-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_created_product_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand', to='product.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('QTY', 'QTY'), ('ITEM', 'ITEM')], default='QTY', max_length=5, verbose_name='Unit'),
        ),
    ]
