# Generated by Django 4.0.3 on 2022-05-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=4, max_digits=8, max_length=8, verbose_name='Quantity'),
        ),
    ]
