# Generated by Django 4.0.3 on 2022-05-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('QTY', 'QTY'), ('ITEM', 'ITEM'), ('KG', 'KG')], default='QTY', max_length=5, verbose_name='Unit'),
        ),
    ]
