# Generated by Django 4.0.3 on 2022-05-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('product', '0012_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('ITEM', 'ITEM'), ('QTY', 'QTY'), ('KG', 'KG')], default='QTY', max_length=5, verbose_name='Unit'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
