# Generated by Django 4.0.3 on 2022-06-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_options'),
        ('product', '0021_product_category_alter_product_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('QTY', 'QTY'), ('ITEM', 'ITEM'), ('KG', 'KG')], default='QTY', max_length=5, verbose_name='Unit'),
        ),
    ]
