version: "3.8"

services:

  db:
    image: "postgres:latest"
    container_name: store-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data/
    networks:
      - public
    tty: true

  metabase-secrets:
    image: metabase/metabase:latest
    container_name: store-metabase
    hostname: metabase-secrets
    ports:
      - 3005:3000
    env_file:
      - .env
    networks:
      - public
    links:
      - db
    tty: true
    volumes:
      - ./db.sqlite3:/db.sqlite3

  redis:
    image: "redis:latest"
    container_name: store-redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - public
    tty: true

  es:
    image: elasticsearch:8.2.0
    hostname: elasticsearch
    container_name: store-es
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - public
    tty: true

#  mongo:
#    image: "mongo:latest"
#    container_name: store-mongo
#    restart: always
#    ports:
#      - 27017:27017
#    env_file:
#      - server/.env
#    networks:
#      - public
#    tty: true
#
#  rabbitmq:
#    image: "rabbitmq:latest"
#    container_name: store-rabbitmq
#    restart: always
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    env_file:
#      - server/.env
#    networks:
#      - public
#    tty: true
#
#  mailhog:
#    image: "mailhog/mailhog"
#    container_name: store-mailhog
#    restart: always
#    driver: none
#    ports:
#      - 1025:1025
#      - 8025:8025
#    networks:
#      - public
#    tty: true

networks:
  public:

volumes:
  postgresdata:
  esdata:
