# Generated by Django 4.0.3 on 2022-06-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('iso3', models.CharField(max_length=5)),
                ('iso2', models.CharField(max_length=5)),
                ('phone_code', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=20)),
                ('currency_name', models.CharField(max_length=20)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
    ]
