# Generated by Django 4.0.3 on 2022-06-10 19:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0018_alter_product_unit'),
        ('basket', '0003_basket_ordered_alter_basket_total_basketitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketItem',
            new_name='BasketItems',
        ),
    ]
