# Generated by Django 4.0.3 on 2022-06-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_state_city'),
        ('customer', '0002_address_created_address_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default=120419, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='address.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default=228, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='address.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default=4279, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='address.state'),
            preserve_default=False,
        ),
    ]
