# Generated by Django 4.0.3 on 2022-06-14 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_address_city_address_country_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Address Line'),
            preserve_default=False,
        ),
    ]
